version: '3'
services:
  db-ca-census:
    container_name: db-ca-census
    image: postgres
    environment:
      POSTGRES_DB: ca_census
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./database:/database/
    working_dir: /database/

volumes:
  database:
